# The numbers generated by the modules may look random in the sense that you cannot predict their subsequent values, but don't forget that they all are calculated using very refined algorithms.

from random import random

for i in range(5):
    print(random())
    

